add_newline = true
format = """
$username\
$hostname\
$shell\
$directory\
$aws\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$jobs\
$character
"""

[hostname]
ssh_symbol = ""
ssh_only = false
format = "[$ssh_symbol on ](bold blue)[$hostname](bold red) "
disabled = false

[aws]
format = 'on [$symbol$profile]($style) '
style = 'bold blue'
symbol = '🅰 '

[shell]
bash_indicator = 'ⓑ '
fish_indicator = '󰈺 '
zsh_indicator = 'ⓩ '
disabled = false
