add_newline = true
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$jobs\
$character
"""

[hostname]
ssh_only = false
format = "[$ssh_symbol on ](bold blue)[$hostname](bold red) "
disabled = false
